### PR TITLE
Change 'master' to 'main'

### PR DESCRIPTION
**Pull request by ElsLommelen**
This PR aims to solve issue #44.
- I already fixed the `.Rmd` files and included pictures, please help me check carefully if I didn't overlook anything.
- I also updated the broken links as far as I could.  However, I was unable to find a replacement for the link to a webinar on 'Github and Rstudio management' in the one but last slide of `course_rstudio.Rmd` (and the same link shows up in the `rstudio.Rmd` slideshow).

@peterdesmet Could you please check if you can find the original presentations?  (While waiting for it, I'll put this PR on draft.)

### CODE REVIEW

**Comment by peterdesmet** [comment]
I have updated the presentations and placed the pdfs in this PR

**Comment by ElsLommelen** [comment]
Thanks @peterdesmet 
Is it possible to update the pictures in the presentation where 'master' is clearly visible, or is it not necessary to do this?  I already changed the majority of the pictures in the repo, so if the presentation contains the same pictures, you can just use these.

**Comment by peterdesmet** [comment]
@ElsLommelen I have updated schemas in the presentation to always say `main` instead of `master` (let me if you still notice some). For the screenshots of GitHub I wouldn't bother updating that.

**Comment by peterdesmet** [comment]
Yes, I think it's fine to leave it like that in the screenshots. We'll hear from users if it is confusing.

Yes, I would rename in this repo. I'll do that right away.

**Comment by ElsLommelen** [comment]
I fixed the broken link and it seems the word 'master' has disappeared from the repo, so I suppose this PR is ready?

**Review by peterdesmet — APPROVED** [review]
Thanks for this update!

**Pull request merged**
